### ISSUE TITLE
Training with 3 codebooks

### ISSUE THREAD

**Issue by yonas-g** [hertz-pj/SNAC-Vocos#6]
Hi,

Thanks for providing the training code. I was wondering if it would be possible to train with 3 codebooks like [this one](https://huggingface.co/hubertsiuzdak/snac_24khz) by changing to the following configs.

```yaml
ratios: [5,4,2]
num_quantizers: 3
rand_num_quant: [4,4,4]
vq_scales: [4,2,1]
```

Thanks!

**Comment by w11wo** [comment]
Hi @yonas-g. I also wanted to do that. I found that this config was able to run:

```yaml
num_quantizers: 3
rand_num_quant: [4,4,4]
vq_scales: [4,2,1]
```

Changing the `ratios` parameter made it OOM all the time. I think that has more to do with the feature extractor's encoder, while the rest is related to the quantizer.
